DotNetCore/Models/Category.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace DotNetCore.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [DisplayName("Category Name")]
        [MaxLength(30)]
        public string Name { get; set; }
        [DisplayName("Display Order")]
        [Range(1,100)]
        public int DisplayOrder { get; set; }
    }
}

DotNetCore/Models/ErrorViewModel.cs
namespace DotNetCore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DotNetCore/Controllers/CategoryController.cs
using DotNetCore.Data;
using DotNetCore.Models;
using Microsoft.AspNetCore.Mvc;

namespace DotNetCore.Controllers
{
    public class CategoryController : Controller
    {
        //We are using ApplicationDbContext by using dependency Injection to show the Category Data.
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<Category> objCategoryList = _db.Categories.ToList();//This code will run like Select * from Category Table it is for getting the all the data from the particular model or table
            return View(objCategoryList);
        }
        public IActionResult CreateCategory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateCategory(Category obj) 
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The Name should not be same to Display Order.");
            }
            if (ModelState.IsValid)
            {
                _db.Categories.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Category Created Successfully";
                return RedirectToAction("Index");
            }
            return View();

        }
        public IActionResult Edit(int? Id)
        {
            if(Id == null || Id==0)
            {
                return NotFound();
            }
            Category? categoryDetails = _db.Categories.Find(Id);
            if (categoryDetails == null)
            {
                return NotFound();
            }
			return View(categoryDetails);
        }
        [HttpPost]
        public IActionResult Edit(Category obj) 
        {
            if (ModelState.IsValid)
            {
                _db.Categories.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Category Updated Successfully";
                return RedirectToAction("Index");
            }
            return View();

        }
        public IActionResult Delete(int? Id)
        {
            if(Id == null || Id==0)
            {
                return NotFound();
            }
            Category? categoryDetails = _db.Categories.Find(Id);
            if (categoryDetails == null)
            {
                return NotFound();
            }
			return View(categoryDetails);
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeletePOST(int? Id) 
        {
            Category deleteCategory = _db.Categories.Find(Id);
            if (deleteCategory == null)
            {
                return NotFound();
            }
            _db.Categories.Remove(deleteCategory);
            _db.SaveChanges();
            TempData["success"] = "Category Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

DotNetCore/Controllers/HomeController.cs
using DotNetCore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DotNetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DotNetCore/Views/Category/CreateCategory.cshtml
@model Category 

<form method="post"> 
    <div class="border p-3 mt-4"> 
        <div class="row pb-2"> 
            <h2 class="text-primary">Create Category</h2> 
            <hr/> 
        </div> 
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="mb-3"> 
            <label asp-for="Name"></label> 
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div> 
        <div class="mb-3"> 
            <label asp-for="DisplayOrder"></label> 
            <input asp-for="DisplayOrder" class="form-control" /> 
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div> 
        <button type="submit" class="btn btn-primary form-control" style="width : 150px">Create</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary form-control" style="width:150px"> Back to List </a>
    </div>
</form>

@* Client side Validation Handling:-*@

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

@* @model Category 
<form method="post"> 
    <div class="border p-3 mt-4"> 
        <div class="row pb-2"> 
            <h2 class="text-primary">Create Category</h2> 
            <hr/> 
        </div> 
        <div class="mb-3 row p-1"> 
            <label asp-for="Name" class="p-0"</label>
            <input asp-for="Name" class="form-control"/>
        </div> 
            <div class="mb-3 row p-1"> 
                <label asp-for="DisplayOrder" class="p-0"></label> 
                <input asp-for="DisplayOrder" class="form-control" /> 
            </div> 
            <div class="row"> 
                <div class="col-6 col-md-3"> 
                    <button type="submit" class="btn btn-primary form-control">Create </button>
                </div> 
<div class="col-6 col-md-3"> *@

DotNetCore/Views/Category/Delete.cshtml
@model Category

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Category</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary form-control" style="width : 150px">Delete</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary form-control" style="width:150px"> Back to List </a>
    </div>
</form>

DotNetCore/Views/Category/Edit.cshtml
@model Category

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Category</h2>
            <hr />
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control" />
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary form-control" style="width : 150px">Edit</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary form-control" style="width:150px"> Back to List </a>
    </div>
</form>

@* Client side Validation Handling:-*@

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

@* @model Category
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Category</h2>
            <hr/>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0"</label>
            <input asp-for="Name" class="form-control"/>
        </div>
            <div class="mb-3 row p-1">
                <label asp-for="DisplayOrder" class="p-0"></label>
                <input asp-for="DisplayOrder" class="form-control" />
            </div>
            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-primary form-control">Create </button>
                </div>
<div class="col-6 col-md-3"> *@

DotNetCore/Views/Category/Index.cshtml
@model List<Category>//By using @model we are connecting or fetching the data from the controller and in the controller we are having index method over there we are getting the data from table.
<div class="container">
	<div class="row pt-4 pb-3">
		<div class="col-6">
			<h2 class="text-primary">
				CATEGORY LIST
			</h2>
		</div>
		<div class="col-6 text-end">
			<a asp-controller="Category" asp-action="CreateCategory" class="btn btn-primary">
				<i class="bi bi-plus-circle"></i>  CREATE NEW CATEGORY
			</a>
		</div>
	</div>
	@* <h1>category list</h1> *@
	<table class="table table-bordered  table-striped">
		<thead>
			<tr>
				<th>
					CATEGORY NAME
				</th>
				<th>
					DISPLAY ORDER
				</th>
				<th>

				</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var obj in Model.OrderBy(x => x.DisplayOrder))//We can simple run the C# code in the cshtml file also we have Model in the foreach loop from there we are connecting to the top @model
			{
				<tr>
					<td>@obj.Name</td> @* Now by using dot notation we can get the particular data *@
					<td>@obj.DisplayOrder</td>
					<td>
						<a asp-controller="Category" asp-action="Edit" asp-route-Id="@obj.Id" class="btn btn-primary">
							<i class="bi bi-pencil-square"></i>
						</a>
					</td>
					<td>
						<a asp-controller="Category" asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-danger">
							<i class="bi bi-trash3-fill"></i>
						</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

DotNetCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DotNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DotNetCore.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DotNetCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" /> @* This partial tag is basically used to get the TempData["success"] and TempData["error"] from the notification you can see the _Notification.cshtml page and also the category controller TempData["success"] and TempData["error"] *@
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="text-center">
            &copy; 2024 - Made with <i class="bi bi-heart-fill"></i> by Chirag Sahu- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DotNetCore/Views/Shared/_Notification.cshtml
@if(TempData["success"]!=null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}